spring.application.name=cleanride
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.ucreyaptetuzkfdlfuuh
spring.datasource.password=Embl4VVqDkr7U1hu
 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.flyway.baselineOnMigrate=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
 
spring.datasource.hikari.maximum-pool-size=5
server.port=${PORT:8080}
 
spring.security.user.name=admin
spring.security.user.password=admin
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.boot.web=DEBUG
 
supabase.url=https://ucreyaptetuzkfdlfuuh.supabase.co
supabase.secret-key=sb_secret_z8BQ6FhR0DrIVqRrS1LPIg_IEF1ixd8
supabase.bucket=Profile_pictures
